services:
  postgres:
    image: postgres:16
    container_name: transcendence_postgres

    env_file:
      - .env
#rediriger le port 5432 de notre machine sur le conteneur PostgreSQL qui ecoute sur son port 5432 
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    env_file:
      - backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    ports:
    - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:

#Docker va buid l'image Docker frontend, puis backend
#Telecharger l'image Postgres si besoin
#Demarrer postgres, backend puis frontend